version: "3"

vars:
  APP_NAME: "scroll4me"
  BIN_DIR: "bin"

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} .

  run:
    desc: Run the application
    cmds:
      - go run .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  bot-test:
    desc: Open bot.sannysoft.com to audit browser fingerprint
    cmds:
      - go run ./cmd/s4m bot-test

  open-config:
    desc: Open config file in default editor
    cmds:
      - go run ./cmd/s4m open config

  open-cache:
    desc: Open cache directory in file explorer
    cmds:
      - go run ./cmd/s4m open cache
