version: "3"

vars:
  APP_NAME: "scroll4me"
  BIN_DIR: "bin"

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} .

  run:
    desc: Run the application
    cmds:
      - go run .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}

  s4m:
    desc: Run dev CLI with any arguments (e.g., task s4m -- bot-test)
    cmds:
      - go run ./cmd/s4m {{.CLI_ARGS}}
