// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AnalysisConfig {
    /**
     * Creates a new AnalysisConfig instance.
     * @param {Partial<AnalysisConfig>} [$$source = {}] - The source object to create the AnalysisConfig.
     */
    constructor($$source = {}) {
        if (!("llm_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["llm_provider"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("relevance_threshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["relevance_threshold"] = 0;
        }
        if (!("batch_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["batch_size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AnalysisConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AnalysisConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AnalysisConfig(/** @type {Partial<AnalysisConfig>} */($$parsedSource));
    }
}

/**
 * Config holds all application configuration
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("interests" in $$source)) {
            /**
             * @member
             * @type {InterestsConfig}
             */
            this["interests"] = (new InterestsConfig());
        }
        if (!("scraping" in $$source)) {
            /**
             * @member
             * @type {ScrapingConfig}
             */
            this["scraping"] = (new ScrapingConfig());
        }
        if (!("analysis" in $$source)) {
            /**
             * @member
             * @type {AnalysisConfig}
             */
            this["analysis"] = (new AnalysisConfig());
        }
        if (!("digest" in $$source)) {
            /**
             * @member
             * @type {DigestConfig}
             */
            this["digest"] = (new DigestConfig());
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {EmailConfig}
             */
            this["email"] = (new EmailConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interests" in $$parsedSource) {
            $$parsedSource["interests"] = $$createField1_0($$parsedSource["interests"]);
        }
        if ("scraping" in $$parsedSource) {
            $$parsedSource["scraping"] = $$createField2_0($$parsedSource["scraping"]);
        }
        if ("analysis" in $$parsedSource) {
            $$parsedSource["analysis"] = $$createField3_0($$parsedSource["analysis"]);
        }
        if ("digest" in $$parsedSource) {
            $$parsedSource["digest"] = $$createField4_0($$parsedSource["digest"]);
        }
        if ("email" in $$parsedSource) {
            $$parsedSource["email"] = $$createField5_0($$parsedSource["email"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

export class DigestConfig {
    /**
     * Creates a new DigestConfig instance.
     * @param {Partial<DigestConfig>} [$$source = {}] - The source object to create the DigestConfig.
     */
    constructor($$source = {}) {
        if (!("morning_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["morning_time"] = "";
        }
        if (!("evening_time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["evening_time"] = "";
        }
        if (!("timezone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timezone"] = "";
        }
        if (!("max_posts_per_digest" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_posts_per_digest"] = 0;
        }
        if (!("include_context" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["include_context"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DigestConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DigestConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DigestConfig(/** @type {Partial<DigestConfig>} */($$parsedSource));
    }
}

export class EmailConfig {
    /**
     * Creates a new EmailConfig instance.
     * @param {Partial<EmailConfig>} [$$source = {}] - The source object to create the EmailConfig.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("smtp_host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtp_host"] = "";
        }
        if (!("smtp_port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["smtp_port"] = 0;
        }
        if (!("smtp_user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtp_user"] = "";
        }
        if (!("smtp_pass" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["smtp_pass"] = "";
        }
        if (!("from_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from_address"] = "";
        }
        if (!("to_address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to_address"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmailConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EmailConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmailConfig(/** @type {Partial<EmailConfig>} */($$parsedSource));
    }
}

export class InterestsConfig {
    /**
     * Creates a new InterestsConfig instance.
     * @param {Partial<InterestsConfig>} [$$source = {}] - The source object to create the InterestsConfig.
     */
    constructor($$source = {}) {
        if (!("keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keywords"] = [];
        }
        if (!("priority_accounts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["priority_accounts"] = [];
        }
        if (!("muted_accounts" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["muted_accounts"] = [];
        }
        if (!("muted_keywords" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["muted_keywords"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterestsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterestsConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keywords" in $$parsedSource) {
            $$parsedSource["keywords"] = $$createField0_0($$parsedSource["keywords"]);
        }
        if ("priority_accounts" in $$parsedSource) {
            $$parsedSource["priority_accounts"] = $$createField1_0($$parsedSource["priority_accounts"]);
        }
        if ("muted_accounts" in $$parsedSource) {
            $$parsedSource["muted_accounts"] = $$createField2_0($$parsedSource["muted_accounts"]);
        }
        if ("muted_keywords" in $$parsedSource) {
            $$parsedSource["muted_keywords"] = $$createField3_0($$parsedSource["muted_keywords"]);
        }
        return new InterestsConfig(/** @type {Partial<InterestsConfig>} */($$parsedSource));
    }
}

export class ScrapingConfig {
    /**
     * Creates a new ScrapingConfig instance.
     * @param {Partial<ScrapingConfig>} [$$source = {}] - The source object to create the ScrapingConfig.
     */
    constructor($$source = {}) {
        if (!("posts_per_scrape" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["posts_per_scrape"] = 0;
        }
        if (!("scrape_interval_hours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scrape_interval_hours"] = 0;
        }
        if (!("headless" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["headless"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrapingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScrapingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrapingConfig(/** @type {Partial<ScrapingConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = InterestsConfig.createFrom;
const $$createType1 = ScrapingConfig.createFrom;
const $$createType2 = AnalysisConfig.createFrom;
const $$createType3 = DigestConfig.createFrom;
const $$createType4 = EmailConfig.createFrom;
const $$createType5 = $Create.Array($Create.Any);
