// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct holds the application state exposed to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

/**
 * GetConfig returns the current configuration (called from frontend)
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * IsAuthenticated checks if X.com credentials are stored
 * @returns {$CancellablePromise<boolean>}
 */
export function IsAuthenticated() {
    return $Call.ByID(3283000736);
}

/**
 * SaveConfig saves the configuration (called from frontend)
 * @param {config$0.Config | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * TriggerDigest manually triggers digest generation and sending
 * @returns {$CancellablePromise<void>}
 */
export function TriggerDigest() {
    return $Call.ByID(2003317659);
}

/**
 * TriggerLogin starts the X.com login flow
 * @returns {$CancellablePromise<void>}
 */
export function TriggerLogin() {
    return $Call.ByID(1326620712);
}

/**
 * TriggerScrape manually triggers a scrape
 * @returns {$CancellablePromise<void>}
 */
export function TriggerScrape() {
    return $Call.ByID(1552808695);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
